apiVersion: apps/v1
kind: Deployment
metadata:
  name: starbuks-deployment
  namespace: pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starbuks
  template:
    metadata:
      labels:
        app: starbuks
    spec:
      containers:
      - name: starbuks
        image: puneetdeshiya1/starbucks:latest
        ports:
        - containerPort: 80
