apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deployment
  namespace: pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotstar
  template:
    metadata:
      labels:
        app: hotstar
    spec:
      containers:
      - name: hotstar
        image: puneetdeshiya1/hotstar:1.0
        ports:
        - containerPort: 80
